CREATE DATABASE IF NOT EXISTS smarthome CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'smarthome'@'%' IDENTIFIED BY 'smarthome';
GRANT ALL PRIVILEGES ON smarthome.* TO 'smarthome'@'%';
FLUSH PRIVILEGES;
